name: Playwright Tests
on:
    workflow_dispatch:
        inputs:
          tests:
            description: "Select which tests do you want to run"
            required: true
            type: choice
            options:
              - all
              - zeuz
              - others
            default: all

jobs:
    test:
        strategy:
          fail-fast: false
          matrix:
            python-version: ["3.10", "3.11", "3.12", "3.13"]
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v3
          
          - name: Set up Python
            uses: actions/setup-python@v4
            with:
              python-version: ${{ matrix.python-version }}

          - name: Install dependencies
            run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

          - name: Install playwright
            run: |
                pip install playwright
                playwright install

          - name: Run all tests
            if: ${{ github.event.inputs.tests == 'all' }}
            run: |
                pytest --tracing retain-on-failure 

          - name: Run zeuz tests
            if: ${{ github.event.inputs.tests == 'zeuz' }}
            run: |
                pytest tests/zeuz --tracing retain-on-failure

          - name: Run other tests
            if: ${{ github.event.inputs.tests == 'others' }}
            run: |
                pytest tests/others --tracing retain-on-failure